<a href="https://colab.research.google.com/github/AhmadFirmanto/Portfolio-pyton/blob/main/tabel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#library

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import random

#dengan random loping

In [ ]:
a = np.array([random.choice(range(30, 60)) for i in range(30)])

df_a = pd.DataFrame({'A' : a})
df_a

#setiap di print datanya berbeda

A
0   34
1   56
2   47
3   42
4   55
5   39
6   57
7   43
8   58
9   51
10  52
11  30
12  59
13  45
14  51
15  39
16  49
17  31
18  53
19  38
20  49
21  50
22  51
23  50
24  59
25  37
26  52
27  36
28  58
29  56

##dengan scipy.stats

In [ ]:
stats.norm(0, 1).rvs(30)

# berdistribusi normal
#rata-rata, standar deviasi
#rvs = random
#setiap di print pasti datanya berbeda

array([-1.17974434,  0.7141259 ,  0.77595397, -0.85698063, -0.5846344 ,
       -1.50216629,  1.82929498, -0.66450459, -0.03993913,  1.29325044,
       -0.41873817,  0.49558055,  0.71186928, -0.31610815,  1.97679787,
        0.02840891,  0.40399735, -0.38815384, -1.07355497, -0.39659604,
       -0.49724105, -0.64674539,  2.00661224, -0.8214268 , -0.59026042,
        0.85421973,  1.36252657, -0.07571576,  1.93383584, -1.98570901])

In [ ]:
np.random.seed(10)

stats.norm(0, 1).rvs(30)

#hasilnya yang di print tetap

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021,
        0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013,
        0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489,
       -1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125,
        1.67262221,  0.09914922,  1.39799638, -0.27124799,  0.61320418])

In [7]:
np.random.seed(5)
stats.poisson(3).rvs(30)

#distribusi poison
#tidak normal

array([2, 5, 1, 3, 2, 4, 2, 3, 0, 3, 1, 7, 6, 0, 1, 5, 5, 0, 2, 2, 5, 3,
       1, 3, 2, 4, 4, 3, 5, 1])